### ISSUE TITLE
Unabale to star logstash as a service

### ISSUE THREAD

**Issue by btalebali** [logstash-plugins/logstash-output-stdout#15]
My Environement includes:

Logstash version: 6.2.4

Operating System : RedHat Entreprise Linux Server release 6.6.

I install Logstash form rpm file but while starting the deamon, I get the following error:

Does it try to require a relative path? That's been removed in Ruby 1.9. 
[ERROR] 2018-06-11 14:21:19.233 [main] Logstash - java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (GemspecError) There was a LoadError while loading logstash-core.gemspec:  
load error: psych -- java.lang.RuntimeException: BUG: we can not copy embedded jar to temp directory from 
  /usr/share/logstash/logstash-core/logstash-core.gemspec:1:in `block in (root)'

Any help please ? 

Regards, 
Béchir

**Comment by jakelandis** [comment]
Closing this issue since it doesn't sound like an issue with the stdout plugin. If you determine it is an issue with the stdout plugin,  please re-open with a corresponding error from the plugin. 

My general advice would be to get it running locally via the .tar.gz (or zip) distribution, then run as a daemon. I haven't seen this error before so I can't help much here....maybe someone over at https://discuss.elastic.co/c/logstash could assist ?
